name: Build DanixOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout danix-kit
        uses: actions/checkout@v4
        with:
          repository: danixtech/danix-kit
          token: ${{ secrets.DANIXKITTOKEN }}
          path: danix-kit
      - name: Verify access
        run: |
          git ls-remote https://x-access-token:${{ secrets.DANIXKITTOKEN }}@github.com/danixtech/danix-kit.git

      - uses: cachix/install-nix-action@v27
      - name: Git status
        run: |
          ls -lah danix-kit
          test -f danix-kit/flake.nix && echo "flake exists"
          git status
          git ls-files | grep danix-kit | head

      - name: Show workspace
        run: |
          pwd
          ls -lah
          find . -maxdepth 2 -type d

      - name: Show flake files
        run: |
          cat flake.nix
          echo
          cat flake.lock
      - name: Show flake metadata
        run: |
          nix flake metadata

      - name: Build ISO
        run: |
          nix build .#iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: danixos-iso
          path: result/*
