name: Build DanixOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Nix GitHub token
        run: |
          mkdir -p ~/.config/nix

          cat > ~/.config/nix/nix.conf <<EOF
          access-tokens = github.com=${{ secrets.DANIXKITTOKEN }}
          EOF

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.DANIXKITTOKEN }}

      #- name: Checkout danix-kit
      #  uses: actions/checkout@v4
      #  with:
      #    repository: danixtech/danix-kit
      #    token: ${{ secrets.DANIXKITTOKEN }}
      #    path: danix-kit
      - uses: cachix/install-nix-action@v27

      - name: Build ISO
        run: |
          nix build .#iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: danixos-iso
          path: result/*
          retention-days: 14
