name: Build DanixOS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Checkout danix-kit
        uses: actions/checkout@v4
        with:
          repository: danixtech/danix-kit
          token: ${{ secrets.DANIXKITTOKEN }}
          path: danix-kit
      - uses: cachix/install-nix-action@v27

      - name: Show workspace
        run: |
          pwd
          ls -lah
          find . -maxdepth 2 -type d

            - name: Build ISO
              run: |
                nix build .#iso

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: danixos-iso
          path: result/*
